---
title: "Fly Body Parts GO Data"
author: "John Santiago"
date: "2023-10-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```




```{r echo = F, warning=F}

library(R.filesets)
library(rrvgo)
library(plotly)

GO.info = read.csv("https://raw.githubusercontent.com/johncsantiago/Fly-Body-Sections-Project/master/Data/GOcat_info.csv", row.names = 1)

GO.sim = function(GO.file){
  GO.data = GO.file[GO.file[,"p.adjust"]<.05,]
  GO.ontology = "BP"
  GO.use = row.names(GO.info)[GO.info$ontology == GO.ontology]
  GO.data = GO.data[intersect(row.names(GO.data), GO.use),]

  go_analysis = row.names(GO.data)

  scores = setNames(-log10(GO.data[,"p.adjust"]), go_analysis)

  simMatrix <- calculateSimMatrix(go_analysis,
                                orgdb="org.Dm.eg.db",
                                ont=GO.ontology,
                                method="Rel")
  return(simMatrix)
}
  
GO.rt = function(GO.file){
  GO.data = GO.file[GO.file[,"p.adjust"]<.05,]
  GO.ontology = "BP"
  GO.use = row.names(GO.info)[GO.info$ontology == GO.ontology]
  GO.data = GO.data[intersect(row.names(GO.data), GO.use),]

  go_analysis = row.names(GO.data)

  scores = setNames(-log10(GO.data[,"p.adjust"]), go_analysis)
  
  go_analysis = row.names(GO.data)

  reducedTerms <- reduceSimMatrix(simMatrix,
                                scores,
                                threshold=0.7,
                                orgdb="org.Dm.eg.db")

  return(reducedTerms)

}

```


```{r echo = F, include = F}
##GO.Sim.PCA function
GO.Sim.PCA = function(use.data){
    pca <- prcomp(t(use.data), scale.=TRUE) 
    pc1=scale(pca$x[,1])
    pc2=scale(pca$x[,2])
    eigs <- pca$sdev^2
    ve=signif(((eigs / sum(eigs))*100)[1:3],4)

    pca.data=data.frame(PC1=pc1,
                        PC2=pc2,
                        sdev=pca$sdev,
                        Percent1=ve[1],
                        Percent2=ve[2],
                        Group = reducedTerms[row.names(use.data), "parentTerm"],
                        Score = reducedTerms[row.names(use.data), "score"],
                        Term = reducedTerms[row.names(use.data), "term"])

    pca.data$Group = factor(pca.data$Group, levels = unique(pca.data$Group))
    pca.data$Score = 20*(1+pca.data$Score/mean(pca.data$Score))
    
  fig  = plot_ly(data = pca.data, 
                 x = ~PC1, 
                 y = ~PC2,
                 name = ~Group,
                 type = 'scatter',
                 mode = 'markers',
                 showlegend = T,
                 color = ~Group,
                 marker = list(size = pca.data$Score,
                               line = list(color = "black", width = 1.5)),
                 hoverinfo = "text",
                 hovertext = paste("Parent Group: ", pca.data$Group,
                                   "\nSample: ", pca.data$Term, 
                                   "\nTotal DE: ", pca.data$TotalDE, 
                                   "\nTotal in Cat.: ", pca.data$Total, 
                                   "\nFDR: ", pca.data$SigVal)) %>%
    layout(xaxis = list(title = paste0("PC1", "(", ve[1], "%)")),
           yaxis = list(title = paste0("PC2", "(", ve[2], "%)")),
           title = "Enriched GO term similarity")
           
  return(fig)
}

```

##Head
```{r echo = F, include=F}

GO.file = read.csv("https://raw.githubusercontent.com/johncsantiago/Fly-Body-Sections-Project/master/Data/GO_Head_df.csv", row.names=1)

simMatrix = GO.sim(GO.file)

reducedTerms = GO.rt(GO.file)

```

```{r fig.height=7, fig.width=10, echo = F}

heatmapPlot(simMatrix,
            reducedTerms,
            annotateParent=TRUE,
            annotationLabel="parentTerm",
            fontsize=6,
            main = "Repressor Gene Enriched Biological Process GO terms")

```


```{r warning=F, fig.width=10, echo = F}

use.data   = simMatrix
GO.Sim.PCA(use.data)

```


```{r fig.align='left', echo = F}

treemapPlot(reducedTerms)

```

##Thorax
```{r echo = F, include=F}

GO.file = read.csv("https://raw.githubusercontent.com/johncsantiago/Fly-Body-Sections-Project/master/Data/GO_Thorax_df.csv", row.names=1)

simMatrix = GO.sim(GO.file)

reducedTerms = GO.rt(GO.file)

```

```{r fig.height=7, fig.width=10, echo = F}

heatmapPlot(simMatrix,
            reducedTerms,
            annotateParent=TRUE,
            annotationLabel="parentTerm",
            fontsize=6,
            main = "Repressor Gene Enriched Biological Process GO terms")

```


```{r warning=F, fig.width=10, echo = F}

use.data   = simMatrix
GO.Sim.PCA(use.data)

```


```{r fig.align='left', echo = F}

treemapPlot(reducedTerms)

```

##Abdomen
```{r echo = F, include=F}

GO.file = read.csv("https://raw.githubusercontent.com/johncsantiago/Fly-Body-Sections-Project/master/Data/GO_Abdomen_df.csv", row.names=1)

simMatrix = GO.sim(GO.file)

reducedTerms = GO.rt(GO.file)

```

```{r fig.height=7, fig.width=10, echo = F}

heatmapPlot(simMatrix,
            reducedTerms,
            annotateParent=TRUE,
            annotationLabel="parentTerm",
            fontsize=6,
            main = "Repressor Gene Enriched Biological Process GO terms")

```


```{r warning=F, fig.width=10, echo = F}

use.data   = simMatrix
GO.Sim.PCA(use.data)

```


```{r fig.align='left', echo = F}

treemapPlot(reducedTerms)

```